### ISSUE TITLE
Potential Enhancements

### ISSUE THREAD

**Issue by srizzling** [cbednarski/hostess#18]
First off great work! I really like this, and it really makes my workflow faster testing and diagnosing issues.

I have two potential enhancements that I would like to propose (I am happy too do them). In order of what I think is important to me (and maybe others)

1) Is there to add a header or commented title saying that this is a modified by hostess, that way you can kind of seperate manual entries (obviously this could be via a external script)

2) An Enhancements, being a way to remove host entries via regex, so a *.google.com or *.github.com would be really good feature to have. For, now I can work around this with a wrapper script but  its bit clunky. 

What do you think?

**Comment by cbednarski** [comment]
Thanks for the feedback!

> 1) Is there to add a header or commented title saying that this is a modified by hostess, that way you can kind of seperate manual entries (obviously this could be via a external script)

What are you trying to do with this? This is the kind of feature that I _could_ add but I don't have a reason to, so I'm curious what you're trying to accomplish.

> 2) An Enhancements, being a way to remove host entries via regex, so a *.google.com or *.github.com would be really good feature to have. For, now I can work around this with a wrapper script but its bit clunky.

Your example uses glob-like syntax rather than regexp. I think this actually makes more sense for hostnames because escaping `.` for regexp would be a bit tedious. I'd be happy to add this for on/off/rm and other commands that make sense to use with multiple hostnames.
