### ISSUE TITLE
Any plan to support group

### ISSUE THREAD

**Issue by alswl** [cbednarski/hostess#31]
Any plan to support group, for example, use a group to manage a group of hosts.

**Comment by cbednarski** [comment]
Are you thinking of glob-like matching on the hostname? Can you give me an example?

Unfortunately `/etc/hosts` does not support wildcard domains like `*.example.com`, though you can use these with `dnsmasq` or a similar tool.

**Comment by alswl** [comment]
@cbednarski 

For example, I have a group named issue_1, when enable this group, a list of domain will enable:

*   a.issue_1.domain.com
*   b.issue_2.domain.com
*   c.domain.com
*   d.test.com

I can use `hostess group on issue_1` to enable all of these domains, and use `hostess group off issue_1` disable all of these domains. And use `hostess group add issue_1 a.domain.com` and `hostess group del issue_1 b.domain` to add or remove domain in group.

**Comment by cbednarski** [comment]
Thanks for clarifying! This is not something I plan to support, because it requires encoding additional metadata into `/etc/hosts` (or another file) to keep track of the groups. I recommend using a bash script instead to enable or disable multiple entries.

However, I would not mind supporting glob-like syntax, as in: https://github.com/cbednarski/hostess/issues/25. That feature may simplify things for you.

**Comment by alswl** [comment]
My solution, use script to manage hosts group.

demo: https://github.com/alswl/.oOo./blob/4a46365177439c729198bc8bd4092d8de6607fa0/.zshrc.etc.d/hosts-on-off.zshrc
