### ISSUE TITLE
Comments and previous order are not considered in new hostfiles

### ISSUE THREAD

**Issue by weshouman** [cbednarski/hostess#36]
OS: Linux
Distro: Ubuntu 16.04
Version: 0.3.0
Arch: amd64

## What happens
Comments and previous order are not persisted in the new generated hostfile.
The new order follows the sorted alphabetical order, which may result in an undesired result if an IP address entry was previously duplicated

## How
Upon running ```hostess add local.example.com 192.168.99.4```.

**Comment by cbednarski** [comment]
Hello, thanks for the report. This is by design.

If you run `hostess fix -n` it will identify duplicates. If you run `hostess fix` (without `-n`) it will arbitrarily decide which one to keep. If you run `hostess add` and there is a duplicate it will simply be replaced with the one you are currently adding.

For example:
```
hostess fix -n
Conflicting hostname entries for waka.pie.local -> 123.123.123.123 and -> 127.0.0.1
```

As for comments, the hostsfile parsing is naive so it does not keep track of which entries might be associated with which comment(s), and also does not keep track of text comments vs. disabled hostfile entries.

This is a limitation of hostess, and if those extra comments are important to you then I'm afraid hostess will not work for your case.
